### ISSUE TITLE
Quality Control exercises a bit unclear

### ISSUE THREAD

**Issue by stephlopezq** [LibraryCarpentry/lc-spreadsheets#1]
The Quality Control section contains a couple points of confusion. Under the Sorting exercise, it says to sort the date by smallest to largest and also the image shows a different variable (wgt). Additionally, for the Conditional Formatting section it would be helpful to say which tab format is under and to clarify the rule for the conditional formatting. However, this may have been a difference between MS Excel on Mac OS which is what I was using for the tutorial.

**Comment by niamhwallace** [comment]
Text says to sort on `date` but image shows `wgt`

**Comment by shlake** [comment]
Confirmed updated.
