### ISSUE TITLE
Lesson Contribution - Add Google Sheets & Update Formatting

### ISSUE THREAD

**Issue by Talishask** [LibraryCarpentry/lc-spreadsheets#109]
I'm a member of The Carpentries staff and I'm submitting this issue on behalf of another member of the community. In most cases, I won't be able to follow up or provide more details other than what I'm providing below.
---
1. Under (Tidy Data for Librarians) in using spreadsheet programs for data organizations, the subheader spreadsheet programs, I would like to add Google Sheets as an option because I see that many library workers are using Google Sheets so this could be an addition.

2. In formatting problems, under subheader multiple tabs (if Google Sheets is added per #1 request), documentation can be added here with this link: Documentation on how to freeze column headers in Google Sheets.

3. Under (Formatting data tables in Spreadsheets) subheader structuring data in spreadsheets , there is a slight typo I noticed. "Different people have entered data in to a spreadsheet." It should be "Different people have entered data into a spreadsheet."

**Comment by ejklein** [comment]
My library also uses Google Sheets as an alternative to Microsoft Excel, and I think adding it helps make the lesson more tool-agnostic.
