### ISSUE TITLE
Broken link in Formatting Problems

### ISSUE THREAD

**Issue by michaelthomasmoore** [LibraryCarpentry/lc-spreadsheets#122]
Hello,

I've noticed a broken link on the Formatting Problems episode (https://librarycarpentry.org/lc-spreadsheets/02-common-mistakes/index.html). In the table of contents, Date Formatting (the final bullet) has a broken link point to https://librarycarpentry.org/03-dates-as-data/index.html.

I believe the correct link is https://librarycarpentry.org/lc-spreadsheets/03-dates-as-data/index.html.

Thank you,
Michael

<details>
<summary><strong>Instructions</strong></summary>

Thanks for contributing! :heart:

If this contribution is for instructor training, please email the link to this contribution to
checkout@carpentries.org so we can record your progress. You've completed your contribution
step for instructor checkout by submitting this contribution!

If this issue is about a specific episode within a lesson, please provide its link or filename.

Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact The Carpentries Team at team@carpentries.org.

You may delete these instructions from your comment.

\- The Carpentries
</details>

**Comment by morskyjezek** [comment]
Hi @michaelthomasmoore - thank you for noting this broken link. We are working to resolve the issue. Please continue to help us improve the lessons from The Carpentries!

**Comment by morskyjezek** [comment]
Resolved in PR #128
