### ISSUE TITLE
Fixing a small typo: adding a comma

### ISSUE THREAD

**Issue by alexandra-wong** [LibraryCarpentry/lc-spreadsheets#127]
In the "Advantages of Alternative Date Formatting" section, the second paragraph starts with "For instance this is a spreadsheet representing insect counts". A comma could be added so that this sentence starts as "For **instance, this** is a spreadsheet representing insect counts".

**Comment by morskyjezek** [comment]
This refers to lc-spreadsheets/_episodes/03-dates-as-data.md - line 149

**Comment by morskyjezek** [comment]
Hi @alexandra-wong - thank you for pointing this out! I am creating a revision to the lesson that will correct this typo, and I am also updating and revising some of the text to explain this example more clearly. Thank you for your help in improving this lesson!

**Comment by morskyjezek** [comment]
Addressed in PR #129
