### ISSUE TITLE
Anchor names with underscores show up in titles

### ISSUE THREAD

**Issue by jcoliver** [LibraryCarpentry/lc-spreadsheets#137]
In episode 2 (and maybe elsewhere) anchors that have an underscore (formatting_pretty and field_name) are showing up in the actual titles. e.g. one title shows up as

### Field name problems {#field_name}

but should probably be

### Field name

Perhaps replacing the underscores with a dash would fix this? Note the underscores are escaped in the markdown document (e.g. `Field name problems {#field\_name}`).

**Comment by morskyjezek** [comment]
Corrected in PR #142
