### ISSUE TITLE
Large font displaying in lists

### ISSUE THREAD

**Issue by morskyjezek** [LibraryCarpentry/lc-spreadsheets#143]
For some reason, the font / type displaying in the lists at the end of the date episode (https://librarycarpentry.org/lc-spreadsheets/03-dates-as-data.html) appear to be larger than any other lists. It's probably a basic formatting error in the markdown file, but I haven't been able to diagnose it. Perhaps something to do with the workbench formatting or R markdown parsing? 

@zkamvar or anyone else might have suggestions?

**Comment by morskyjezek** [comment]
This seems to be happening because a CSS rule for the #resources ID section implements .2px instead of the font-weight: 400 rule. I'm trying to get around that by calling the section "Further Resources".

**Comment by morskyjezek** [comment]
Appears to be resolved in PR #144 .

**Comment by zkamvar** [comment]
Thank you for catching this! I've opened an issue in {varnish} to track it: https://github.com/carpentries/varnish/issues/85
