### ISSUE TITLE
Consider more current resources for additional learning

### ISSUE THREAD

**Issue by maneesha** [LibraryCarpentry/lc-spreadsheets#150]
### How could the content be improved?

The [spreadsheets intro lesson](https://datacarpentry.org/spreadsheet-ecology-lesson/00-intro.html) suggests [Head First Excel](https://www.amazon.com/Head-First-Excel-learners-spreadsheets/dp/0596807694/), published by O’Reilly for additional learning. This book is 14 years old (publication date April 2010). I do not use Excel but I am assuming much of the content is outdated. Consider replacing this with a more current resource.

Note this is essentially a duplicate of https://github.com/datacarpentry/spreadsheet-ecology-lesson/issues/336 and https://github.com/datacarpentry/spreadsheets-socialsci/issues/168

### Which part of the content does your suggestion apply to?

https://datacarpentry.org/spreadsheet-ecology-lesson/00-intro.html

**Comment by morskyjezek** [comment]
Thanks for the suggestion and the fix!
