### ISSUE TITLE
Curriculum Request: Add estimated length of lesson

### ISSUE THREAD

**Issue by chennesy** [LibraryCarpentry/lc-spreadsheets#158]
### How could the content be improved?

The LC-CAC recently updated the [LC lessons page](https://librarycarpentry.org/lessons/) to add a column with an estimated length for each lesson that workshop organizers can use to help them plan workshops. We used estimated times from the [YAML `teaching` and `exercises` metadata fields ](https://carpentries.github.io/sandpaper-docs/episodes.html#yaml-metadata)from your lesson to come up with the initial estimated length. Two requests:

1. Please reply here if you want to suggest a different estimated length for the lessons page and I will update the lessons page.
2. If our estimate was incorrect, it would be great if you can update the episode YAML metadata to reflect more accurate times.

**Comment by morskyjezek** [comment]
Hi @chennesy - thanks this is a nice addition to the main site. I estimate 2.5 to 3 hours, based on the provided data. I have found 3 hours to be typical, basically a half day workshop. The main site says 2-3 hours, which is probably a good ballpark number.
