### ISSUE TITLE
Why not use KNIME for data manipulation

### ISSUE THREAD

**Issue by StephanJanosch** [LibraryCarpentry/lc-spreadsheets#16]
Hi,

did you ever consider using [KNIME](http://knime.com/) as tool for data manipulation? I think the approach via Knime is way more reproducible and also visually more appealing.

Just my 2c,
Stephan

**Comment by cmacdonell** [comment]
Hi Stephan, I haven't heard of KNIME before thanks for the note about it. I think it could be useful as a separate lesson. As for this lesson, which is an introduction, I think the connection with Excel, which is familiar to most, is fairly important. I think a follow-on lesson about a potentially "better tool" is an option. 

Is KNIME completely open-source?

**Comment by shlake** [comment]
Hi @StephanJanosch thanks for the interest in the Library Carpentry Tidy Data Lesson. I had not heard about KNIME; thanks for brining that to our attention. 

At this point spreadsheet programs are more familiar and used more in the Library world. So at this time, we will stick with the basics (excel/LibreOffice) on teach how to best use this tool for creating archivable, re-usable, tidy data.
