### ISSUE TITLE
Caveats of popular data and file formats - broken links

### ISSUE THREAD

**Issue by fionajones** [LibraryCarpentry/lc-spreadsheets#17]
In the "Caveats of popular data and file formats" episode there are 3 broken links:
1. Under "Commas as part of data values in *.csv files"
In the **previous lesson** we discussed... 
The link for previous lesson is broken.
2. Under "Dealing with commas as part of data values in .csv files"
This **example data file** applies this rule...
The link for example data file is broken.
2. Under "Dealing with commas as part of data values in *.csv files"
Open the **species.csv** file in Excel (or Calc in Libre Office). 
The link for species.csv is broken.  

---

**Comment by shlake** [comment]
Confirmed fixed
