### ISSUE TITLE
Setup file refers to specific version of LibreOffice

### ISSUE THREAD

**Issue by duchessanne** [LibraryCarpentry/lc-spreadsheets#2]
Setup file refers to 4.4.2 of LibreOffice but the latest version is 6.0.4. Is it worth listing software version at all if LibreOffice is updated regularly?

**Comment by libcce** [comment]
In other lessons, I've seen listing software without version and I would agree with you to leave it out. We could include a note regarding checking the version but we can leave this out.

**Comment by niamhwallace** [comment]
Maybe we could make the language generalizable, like: "Click the green download button to download the latest version."
