### ISSUE TITLE
Training attendance data includes RANDBETWEEN formula

### ISSUE THREAD

**Issue by jcoliver** [LibraryCarpentry/lc-spreadsheets#22]
In the second sheet, "2017", column J includes a formula which looks to be used to generate data. It fills the value of the cell with a random number between 15 and the number of registrants (column I). I couldn't find a place in the lesson where this formula is used, and in copy/pasting, it seemed to just cause confusion in the workshop. Perhaps the spreadsheet could be updated so numerical values, rather than a formula, are present in cells I4:I12 of sheet "2017"?

**Comment by shlake** [comment]
Yes, the formula needs to removed from the spreadsheet.
