### ISSUE TITLE
New maintainers needed!

### ISSUE THREAD

**Issue by jezcope** [LibraryCarpentry/lc-spreadsheets#26]
As we look to move Library Carpentry to becoming a formal part of the Carpentries community, we need to make sure that each of our lessons are properly supported, including 3 maintainers for each one. It will also be obvious to anyone paying attention that I haven't had much time to work on this lesson recently, and that will be the case for a while, so I'm looking to step down from that responsibility for now.

I'm particularly pinging the following people who have contributed issues and pull requests to this repository but anyone with an understanding of the content and the library world would be welcome.

@duchessanne @cmacdonell @niamhwallace @shlake @yvonnemery @libcce @fmichonneau @stephlopezq @stephanjanosch @fionajones @jcoliver

**Comment by shlake** [comment]
@jezcope I can be one of the 3 maintainers for this lesson. Did anyone else speak up?

**Comment by shlake** [comment]
New Maintainers @shlake @tpatwood @jt14den and Erika Mias 
Meeting and review starting week of April 29, 2019
