### ISSUE TITLE
Sorting Question: Puzzled about one of the questions

### ISSUE THREAD

**Issue by danmichaelo** [LibraryCarpentry/lc-spreadsheets#29]
Hi, we're planning to teach this on Tuesday, but there's an exercise I'm not sure if I understand myself under [Sorting](https://librarycarpentry.github.io/lc-spreadsheets/04-quality-control/index.html#sorting) :O

The question is "When you do this sort, do you notice anything strange?", but when I sort the date column, it seems to sort perfectly, I don't see anything strange. Is it perhaps just supposed to be strange that it sorts perfectly without *showing* the year..?

Or could it be that the exercise does not match the current version of the spreadsheet? The screenshot does not match the current spreadsheet at all.

**Comment by danmichaelo** [comment]
Didn't notice anything strange about the other columns either (second part of the question..) :/

**Comment by danmichaelo** [comment]
@jezcope

**Comment by jezcope** [comment]
Hi @danmichaelo, sorry for the delay. I wonder if someone at some point has accidentally committed a fixed version of the spreadsheet: from memory the rows ought to sort into a noticeably incorrect order because of inconsistencies in the data entry.

**Comment by weaverbel** [comment]
Should be possible to revert to an earlier version of the data file?

**Comment by shlake** [comment]
I see that there isn't a solution for the exercise and wonder if the exercise has been proofed. Will look at this.

**Comment by jt14den** [comment]
This exercise was based on data carpentry ecology sorting exercise: https://datacarpentry.org/spreadsheet-ecology-lesson/04-quality-control/index.html#sorting where there is a column that has mixed types (alphanumeric and numerics).  I'll update both the spreadsheet to introduce this in the `len_hours` column with values like `1.5 hours` and `90 minutes` and the exercise so it matches the goal of using sort to find those.
