### ISSUE TITLE
Set up page is not formatted properly

### ISSUE THREAD

**Issue by weaverbel** [LibraryCarpentry/lc-spreadsheets#32]
There is an issue on this page - the formatting is broken

https://librarycarpentry.org/lc-spreadsheets/setup/

**Comment by libcce** [comment]
Thanks @weaverbel! It's been fixed https://librarycarpentry.org/lc-spreadsheets/setup.html via https://github.com/LibraryCarpentry/lc-spreadsheets/commit/eb979bb8f76cde61b598e98dbc3f045eceed3a93
