### ISSUE TITLE
Dates as data - adding ISO standard

### ISSUE THREAD

**Issue by cjbakker** [LibraryCarpentry/lc-spreadsheets#33]
In the "storing dates as a single string" section, I would suggest modifying the last sentence as follows:

"You could also use the 'YYYYMMDD' format. YYYYMMDD is an international standard (ISO 8601) and can eliminate ambiguity when sharing spreadsheets. Such strings will be correctly sorted in ascending or descending order, and by knowing the format they can then be correctly processed by the receiving software."

The word ascending is also currently misspelled (missing the "i").

**Comment by shlake** [comment]
Will look at the lesson and incorporate the ISO standard (that's what YYYYMMDD is) in this section: **"Storing dates as a single string"**. Will make it more explicit.

**Comment by shlake** [comment]
Added ISO standard info in @shlake branch (to be merged soon).
