### ISSUE TITLE
Suggested objectives (submitted by Heather James via email)

### ISSUE THREAD

**Issue by ErinBecker** [LibraryCarpentry/lc-spreadsheets#34]
Using spreadsheet programs for data wrangling (https://librarycarpentry.org/lc-spreadsheets/00-intro/index.html)

Suggested Objectives:
i. Discuss the variety of ways that spreadsheets function as tools in our daily work

ii. Distinguish machine readable tidy data from data that is easy to read for humans

iii. Articulate the purpose and importance of data cleaning as a primary and substantial step in working with data

**Comment by erikamias** [comment]
Thanks Heather: Agreed, (especially re:iii) will have a look at this in the lesson material (as well as some guidance in the instructor notes) on how to tailor this discussion for future workshops in relation to the coverge given in the "Intro to Data" lesson with the other maintainers.
