### ISSUE TITLE
Change Delimiter on PDR/PDRA/other Column

### ISSUE THREAD

**Issue by shlake** [LibraryCarpentry/lc-spreadsheets#38]
When trying to use the Text-to-Columns feature to separate the PGR/PDRA/Other column into three new columns, Excel get confused and thinks the "/" is part of a date (and we know how dates are not easy or totally understood in Excel).
Suggesting that a new delimiter, possibly "|" is used.

**Comment by shlake** [comment]
@jcoliver changed the heading for the PGR|PDRA|Other column, but all the numbers in the column also need to be delimited by "|" (taking out the "/" in that column - which causes Excel to think they are dates).

Will update the datafile and PR the delimiter change.

**Comment by jcoliver** [comment]
Ah, heck. I should have noticed that. Good catch, @shlake .
