### ISSUE TITLE
Formatting Problems Lesson Needs New Screenshots

### ISSUE THREAD

**Issue by shlake** [LibraryCarpentry/lc-spreadsheets#39]
This lesson uses screen shots from the Data Carpentry sample file. 

For this Library Carpentry lesson, the sample file is "training_attendance", so this lesson needs equivalent screen shots from the training_attendance file.

**Comment by jcoliver** [comment]
There are accompanying parts of the lesson text that also need updating, as they, too, refer to the data set from the DC lesson.
