### ISSUE TITLE
Dates as data - text is outdated

### ISSUE THREAD

**Issue by duchessanne** [LibraryCarpentry/lc-spreadsheets#5]
"If Excel was to be believed, this person had been collecting bugs IN THE FUTURE. Now, we have no doubt this person is highly capable, but I believe time travel was beyond even his grasp."
--The most recent example in the table is 2017. Include a new example table, maybe with a date of Jul-31 - the "How it was interpreted" column will be 1-Jul-31 so it'll be a few years before this is outdated again. :)

**Comment by jcoliver** [comment]
Image from Excel/LibreOffice should be updated on  lc-spreadsheets/_episodes/03-dates-as-data.md

**Comment by arminstraube** [comment]
If these two sentences are removed the lesson flows smoothly: 

> "If Excel was to be believed, this person had been collecting bugs IN THE FUTURE. Now, we have no doubt this person is highly capable, but I believe time travel was beyond even his grasp."
