### ISSUE TITLE
Find an OA option for a good reference on statistics/plotting/write code

### ISSUE THREAD

**Issue by tpatwood** [LibraryCarpentry/lc-spreadsheets#50]
Under "What this lesson will not teach you" the lesson points to a link to an O'Reilly Media book on Amazon. If there's an OA alternative we should link to that instead, but it's also okay to just keep it as-is... 

Here: https://librarycarpentry.org/lc-spreadsheets/00-intro/index.html#what-this-lesson-will-not-teach-you

**Comment by libcce** [comment]
I've always been a fan of Lynn Cherny... She taught a course that points to some resources (2nd to last slide) https://www.dropbox.com/s/oe27xy1lpg6vx55/ExcelDataClass.zip?dl=0&file_subpath=%2FExcelDataClass%2FExcel+Tips+Data.pdf Maybe the resources she points to are helpful?

**Comment by doingarchives** [comment]
Whatever the solution, we should look to shorten these URLs using bitly. Is there a ‘branded’ bitlink for carpentries in general or library carpentry specifically?

**Comment by carrlucy** [comment]
Here are some OA texts/tutorials for Excel:

- Beginning Excel 2019 [https://openoregon.pressbooks.pub/beginningexcel19/]
- GCF Global Excel 2016 [https://edu.gcfglobal.org/en/excel2016/]

Additionally, here are Microsoft's own tutorials for Excel: [https://support.microsoft.com/en-us/office/excel-video-training-9bc05390-e94c-46af-a5b3-d7c22f6990bb?]

**Comment by morskyjezek** [comment]
This is also a paid resource, but it may be of particular interest since it is specifically about using Excel for work with library collections: https://www.alastore.ala.org/content/analyzing-library-collection-use-excel%C2%AE

It's also from ALA.
