### ISSUE TITLE
Dates as Data - confusing exercise

### ISSUE THREAD

**Issue by duchessanne** [LibraryCarpentry/lc-spreadsheets#6]
_This activity is confusing - and maybe distracting from the main learning objective of formatting dates correctly with month, day, and year in separate columns, especially because Excel functions aren't addressed in the earlier lessons.

I would put this text above the exercise:_
**Preferred date format
Instead it is much safer to store dates with MONTH, DAY and YEAR in separate columns or as YEAR and DAY-OF-YEAR in separate columns.**

_And maybe add a faded example, or slightly more detailed example syntax:_
________________________
Current time and date are best retrieved using the functions NOW(), which returns the current date and time, and TODAY(), which returns the current date. The results will be formatted according to your computer’s settings.

- **In an empty cell, t**ry to extract the year, month and day from the current date and time string returned by the NOW() function. 
**--=YEAR(NOW())
--=MONTH( ____ ())
--= ____ ( ____ ())**

- Calculate the current time using NOW()-TODAY(). **Note that the default output will be a decimal, not in the hh:mm:ss format.**

- Try to extract the hour, minute and second from the current time using functions HOUR(), MINUTE() and SECOND().

- press **fn** + F9 to force the spreadsheet to recalculate the NOW() function, and check that it has been updated.
___________________________

_And then keep the note about Excel and pre-1900 dates where it is._

**Comment by PhilReedData** [comment]
I agree with @duchessanne, however I would write the last bullet point differently. Some keyboards will need you to press fn + F9, and some just F9 without a modifier. So I suggest:

- Press F9 to force the spreadsheet to recalculate the NOW() function, and check that it has been updated. Note, on some keyboards you may need to press Fn + F9 keys together.
