### ISSUE TITLE
Broken links in Contributing.md

### ISSUE THREAD

**Issue by s-canchi** [LibraryCarpentry/lc-spreadsheets#60]
Here are set of broken links on this page:
1. 'code of conduct' - under Contributor Agreement section
2. 'creating an issue' - under How to contribute section
3.  'https://github.com/swcarpentry/FIXME' - both the links referencing this website in the first numbered point under the Where to Contribute section
4. 'bug reports' - under What to Contribute section
5. 'list of issue for this repository' - under What to Contribute section
6. 'master repository' - Both the references under the Using Github section
7. 'discussion mailing list' - Not sure if it broken but goes to a blank page with 'No route defined for this request...' in an empty box and clicking the Back home box didn't reroute.

**Comment by jt14den** [comment]
Fixed with #62, Thanks @s-canchi & @serahrono
