### ISSUE TITLE
Screen shots for Windows

### ISSUE THREAD

**Issue by ErinBecker** [LibraryCarpentry/lc-spreadsheets#61]
Submitted by email for Instructor Training checkout:
---------
In reviewing some of the Library Carpentry lessons as part of the check-out process for the instructor training I noticed an issue.

In the following lesson:
https://librarycarpentry.org/lc-spreadsheets/05-exporting-data/index.html

and this may be the case in others, it would be useful to include screen snapshots of Windows version of software. I think it would be especially useful in these lessons where Excel is being used, the Mac and Windows interface can be different (depending on what you're doing). Also, my experience is that a good number of people taking Library Carpentry are developing their computer skills and it is a stretch for some to figure out the difference between the Mac and Windows interfaces.

Understanding that the page is already loaded with information, I'm not sure where this would fit on the page. It may not be necessary for all screen snapshots, just for the ones where the Windows and Mac versions differ.

Another alternative is that when teaching the lessons live, suggest that the instructors have access to and are able to display different software versions (Mac v. Windows).

I hope this makes sense. It's based off of my experience working with people who are novices.

**Comment by jt14den** [comment]
I'll add windows screenshots if someone can provide them.

**Comment by kenlacey** [comment]
Hi Tim
Are these of use?
Ken

[Images.zip](https://github.com/LibraryCarpentry/lc-spreadsheets/files/4690044/Images.zip)

**Comment by jt14den** [comment]
Thanks @kenlacey. I'll work on getting them into the lessons.

**Comment by morskyjezek** [comment]
Hi @jt14den - it looks like some of these are added. Is this issue ready to close? I recently completed the Maintainers Onboarding, was assigned to the lc-spreadsheets lesson, and am trying to get up to speed on the open issues. 

Happy to be joining you!

**Comment by jt14den** [comment]
Hey @morskyjezek . Sorry I missed this. This is ready to close.
