### ISSUE TITLE
Link to wrong data file

### ISSUE THREAD

**Issue by arminstraube** [LibraryCarpentry/lc-spreadsheets#68]
In the **Caveats of popular data and file formats** part of the lesson (https://librarycarpentry.org/lc-spreadsheets/06-data-formats-caveats/index.html) under the heading **Dealing with commas as part of data values in .csv files** there is a link to an example data file (https://ndownloader.figshare.com/files/3299483). This linked file is different from the excerpt described in this section. 

I would suggest removing the link. The lesson could just work with the data given in text form in this section.

**Comment by shlake** [comment]
Suggestion to not include this as a separate episode - so wouldn't need to have links to files to download. 

Data Carpentry Ecology Lesson removed this episode, added a paragraph in the Exporting episode and made the previous episode 6 a "Discussion" (extra): https://datacarpentry.org/spreadsheet-ecology-lesson/discuss/index.html
