### ISSUE TITLE
Suggested new title for "Basic Quality Assurance and Control, and Data Manipulation in Spreadsheets"

### ISSUE THREAD

**Issue by sararasmussn** [LibraryCarpentry/lc-spreadsheets#74]
Hi there! Thank you for all the work you do to make this resource available to everyone! 
This is my first issue submission as part of the Carpentries trainer check-out process. 

For the episode ["Basic Quality Assurance and Control, and Data Manipulation in Spreadsheets"](https://librarycarpentry.org/lc-spreadsheets/04-quality-control/index.html), I have a few suggestions. (Edit: At the guidance of the Carpentries onboarding team I'm breaking this up into separate issues 1/2/2020.)

**Episode title:**
- My first suggestion would be to simplify the title. Compared to the others, this one runs long. Perhaps eliminate "basic" for the same reason we avoid "just", "simple," etc. Data manipulation doesn't add much, as the lesson itself is divided by the two sections, QA and QC. I think reinforcing the language in the title and headers helps learners.  
- I would suggest: _"Ensuring Quality Assurance and Quality Control."_

**Comment by shlake** [comment]
Great idea.
Will change title when @shlake branch is merged 
See #90

**Comment by shlake** [comment]
Duplicate issue to #90 will update when that issue is closed.
