### ISSUE TITLE
Suggestions for Quality Control section of "Basic Quality Assurance and Control, and Data Manipulation in Spreadsheets"

### ISSUE THREAD

**Issue by sararasmussn** [LibraryCarpentry/lc-spreadsheets#75]
For the episode ["Basic Quality Assurance and Control, and Data Manipulation in Spreadsheets"](https://librarycarpentry.org/lc-spreadsheets/04-quality-control/index.html), I would suggest these edits to the Quality Control section:
- The tip about version control and the readme paragraph below are related, but it's not clear whether these are theoretical concepts to be explained to learners, or whether they are part of the hands-on process. 
- If time allows, I would suggest incorporating hands-on steps because then learners have practice with the idea presented. At the very least, an example in the narrative would help illustrate each of these steps, maybe broken into a numbered list because while brief, these paragraphs pack a lot of information. 
- Stylistically, I would suggest making these the same text format; one as a tip and one as a free-floating paragraph is a little disjointed. 

Thank you for your consideration!

**Comment by morskyjezek** [comment]
Hi @sararasmussn - thanks for these observations and suggestions! We're always happy to get this sort of feedback and input on the Library Carpentry materials. You make a good point, and in looking over this section of the lesson, I agree that the "Tip!" and advice about readme are not well integrated into the flow of the lesson. The placement in the flow of the lesson A related point was raised about the conflicting advice throughout the lesson about logging actions (#36 ) which in some points is described as a step in a new sheet, and is also mentioned as a separate file. In any case, I see this point as related to the larger issue. For the moment, we haven't been able to address this comment, but I think that we hope to in the near future, so leaving this issue open as a reminder.

**Comment by morskyjezek** [comment]
Thank you again for this suggestion. The issue has been open for some time, and as I'm reviewing suggestions and changes, this one seems to be addressed in the new PR #155 - this change suggested use of the README was the required option (removed the ambiguity), and it also provides some specific examples about what to put in the README.
