### ISSUE TITLE
Typo in Key Points section of Basic Quality Assurance and Control, and Data Manipulation in Spreadsheets

### ISSUE THREAD

**Issue by sararasmussn** [LibraryCarpentry/lc-spreadsheets#76]
Typo in Key Points section of ["Basic Quality Assurance and Control, and Data Manipulation in Spreadsheets"](https://librarycarpentry.org/lc-spreadsheets/04-quality-control/index.html) episode:

- We have a typo in the second bullet; possibly should be possible: 
"Use sorting and conditional formatting to identify **possibly** errors."

**Comment by shlake** [comment]
Fixed in @shlake branch (to be merged soon).
